name: .NET 8 CI/CD Pipeline

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master
      - feature/**

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build-test
    if: github.ref == 'refs/heads/master' && success()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish app
        run: dotnet publish HelloWorld/HelloWorld.csproj -c Release -o publish

      - name: Mock Deploy (Simulated Deployment)
        run: |
          echo "Starting mock deployment..."
          mkdir -p /tmp/mock-deploy/
          cp -r publish/* /tmp/mock-deploy/
          echo "Files copied to /tmp/mock-deploy/ (Mock Deployment Complete)"
